Nimap Asignment Codefirst/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nimap_Asignment_Codefirst.Controllers
{
        public class HomeController : Controller
    {
        public ActionResult Index()
        {


            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
	
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
	ViewBag.Status = "Ok";
            return View();
        }


    }
}  

Nimap Asignment Codefirst/Controllers/RoleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Nimap_Asignment_Codefirst.Context;
using Nimap_Asignment_Codefirst.Models;
using Nimap_Asignment_Codefirst.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Nimap_Asignment_Codefirst.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {

        private Usermanager _usermanager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<Usermanager>();
            }
        }

        private AppRolemanager _rolemanager
        {
            get
            {
                return HttpContext.GetOwinContext().Get<AppRolemanager>();
            }
        }

        public RoleController()
        {

        }


        #region RoleCRUD
        public async Task<ActionResult> RoleList()
        {
            var rolesList = await _rolemanager.Roles.ToListAsync();
            return View(rolesList);
        }


        [HttpGet]
        public ActionResult RoleCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> RoleCreate(RoleModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole()
                {
                    Name = model.RoleName
                };

                var result = await _rolemanager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("RoleList");
                }


            }

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> RoleEdit(string id)
        {
            var role = await _rolemanager.FindByIdAsync(id);
            RoleModel model = new RoleModel()
            {
                RoleId = role.Id,
                RoleName = role.Name

            };

            return View(model);
        }


        [HttpPost]
        public async Task<ActionResult> RoleEdit(RoleModel model)
        {

            IdentityRole role = new IdentityRole()
            {
                Id = model.RoleId,
                Name = model.RoleName
            };
            var result = await _rolemanager.UpdateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("RoleList");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> RoleDelete(string id)
        {
            var role = await _rolemanager.FindByIdAsync(id);
            var result = await _rolemanager.DeleteAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("RoleList");
            }
            return View();
        }

        #endregion

        #region Users to Role 



        [HttpGet]
        public async Task<ActionResult> AddRoleToUsers(string id)
        {

            ViewBag.RoleId = id;

            var role = await _rolemanager.FindByIdAsync(id);
            ViewBag.RoleName = role.Name;
            var model = new List<UserRoleModel>();


            foreach (var user in _usermanager.Users.ToList())
            {
                UserRoleModel userRoleModel = new UserRoleModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };


                if (await _usermanager.IsInRoleAsync(user.Id, role.Name))
                {

                    userRoleModel.IsSelected = true;
                }
                else
                {
                    userRoleModel.IsSelected = false;
                }



                model.Add(userRoleModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> AddRoleToUsers(List<UserRoleModel> model, string roleid)
        {
            if (model != null)
            {
                var role = await _rolemanager.FindByIdAsync(roleid);

                for (int i = 0; i < model.Count; i++)
                {

                    var user = await _usermanager.FindByIdAsync(model[i].UserId);

                    IdentityResult result = null;

                    if (model[i].IsSelected && (!await _usermanager.IsInRoleAsync(user.Id, role.Name)))
                    {
                        result = await _usermanager.AddToRoleAsync(user.Id, role.Name);

                    }
                    else if ((!model[i].IsSelected) && (await _usermanager.IsInRoleAsync(user.Id, role.Name)))
                    {

                        result = await _usermanager.RemoveFromRoleAsync(user.Id, role.Name);
                    }
                    else
                    {
                        continue;
                    }

                    if (result.Succeeded)
                    {
                        if (i < (model.Count - 1))
                        {
                            continue;
                        }
                        else
                        {
                            return RedirectToAction("Rolelist");
                        }
                    }
                }

            }
            return RedirectToAction("Rolelist");

        }
        #endregion



    }
}

Nimap Asignment Codefirst/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Nimap Asignment Codefirst/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Nimap Asignment Codefirst/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div>
    <b>Index Page-Home</b>

    @if (Request.IsAuthenticated)
    {

        if (User.IsInRole("Admin"))
        {
            <div class="jumbotron">
                <h2><b>ADMIN</b></h2>
                <h3 class="pull-right text-right"><b>Hi @User.Identity.Name.ToString()</b></h3>
            </div>

            <div class="center-block text-center">
                <h3>
                    You Have Access To Category Mnagement, ,Click Here for Category List @Html.ActionLink("Category", "CategoryList", "Category")
                </h3>
            </div>

            <div class="center-block text-center">
                <h3>
                    You Have Access To Role Mnagement, ,Click Here for Role List @Html.ActionLink("Roles", "RoleList", "Role")
                </h3>
            </div>
        }
        else if (User.IsInRole("Supervisor"))
        {
            <div class="jumbotron">
                <h2 class="text-info"><b>Supervisor</b></h2>
                <h3 class="pull-right text-right"><b>Hi @User.Identity.Name.ToString()</b></h3>
            </div>

            <div class="center-block text-center">
                <h3>
                    You Have Access To Product Management ,Click Here for Product List @Html.ActionLink("Product", "ProductList", "Product")
                </h3>
            </div>
        }
    }
</div>